<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
<xsl:output method="html" doctype-system="about:legacy-compat" indent="yes" />
<xsl:template match="/">
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>XML Sitemap | Syntax Toolbox</title>
		<style>
			*,
			*::before,
			*::after {
				box-sizing: border-box;
				margin: 0;
			}
			* {
				padding: 0;
			}
			html {
				scroll-behavior: smooth;
			}
			body {
				font-family: Inter, ui-sans-serif, system-ui, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji;
				font-size: 16px;
				line-height: 24px;
				color: #282C34;
				max-width: 1200px;
				margin: 0 auto;
				background-color: #F8F9FE;
				-webkit-font-smoothing: antialiased;
				-moz-osx-font-smoothing: grayscale;
			}
			p {
				margin-top: 1rem;
				margin-bottom: 1rem;
			}
			strong {
				font-weight: 700;
			}
			h1 {
				font-size: 2.25rem;
				line-height: 2.5rem;
				color: #1B56FD;
				border-bottom: 1px solid #0243fc;
				margin-top: 2.25rem;
				margin-bottom: 1.5rem;
				padding-bottom: 1rem;
			}
			a {
				color: #1b56fd;
				text-decoration: none;
				font-weight: 500;
			}
			a:hover {
				text-decoration: underline;
				color: #023de3;
			}
			table {
				display: grid;
				grid-template-columns: 3.75fr 1.5fr 1.25fr 0.75fr; /* Adjusted column widths */
				width: 100%;
				border-collapse: collapse;
				margin-top: 1.5rem;
				margin-bottom: 4rem;
				box-shadow: rgba(0, 0, 0, 0.1) 0px 1px 3px, rgba(0, 0, 0, 0.06) 0px 1px 2px;
				background-color: white;
				border-radius: 0.5rem;
				overflow: hidden; 
			}
			thead,
			tbody,
			tr {
				display: contents;
			}
			th, td {
				padding: 16px 20px;
				border-bottom: 1px solid #f4f7ff;
				text-align: left;
			}
			th {
				background-color: #1B56FD;
				color: white;
				font-weight: 600;
			}
			tr:hover td {
				background-color: #eff3ff;
			}
			.priority-high {
				color: #1DB954;
				font-weight: 600;
			}
			.priority-medium {
				color: #FEBE10;
				font-weight: 600;
			}
			.priority-low {
				color: #64748b;
				font-weight: 600;
			}
		</style>
	</head>
	<body>
		<h1>XML Sitemap</h1>
		<p>This XML Sitemap was automatically generated by <a href="https://thegeeekytutor.netlify.app" target="_blank">Syntax Toolbox</a> to assist search engines in efficiently crawling and indexing website content - including tools, articles, and other valuable resources. Sitemaps improve visibility across search engines like <a href="https://search.google.com/search-console/sitemaps" target="_blank" rel="noopener">Google</a> and <a href="https://www.bing.com/webmasters/sitemaps" target="_blank" rel="noopener">Bing</a> by regularly updating them with the latest pages.</p>
		<p>You can find more information about XML sitemaps on <a href="https://sitemaps.org/" target="_blank" rel="noopener">sitemaps.org</a>.</p>
		<p>This XML Sitemap Index file contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)" /></strong> URLs.</p>
		<table>
			<thead>
				<tr>
				<th>URL</th>
				<th>Last Modified</th>
				<th>Change Frequency</th>
				<th>Priority</th>
				</tr>
			</thead>
			<tbody>
				<xsl:for-each select="sitemap:urlset/sitemap:url">
				<tr>
					<td>
						<a href="{sitemap:loc}">
							<xsl:value-of select="sitemap:loc" />
						</a>
					</td>
					<td>
						<xsl:value-of select="sitemap:lastmod" />
					</td>
					<td>
						<xsl:value-of select="sitemap:changefreq" />
					</td>
					<td>
						<xsl:attribute name="class">
							<xsl:choose>
							<xsl:when test="sitemap:priority >= 0.9">priority-high</xsl:when>
							<xsl:when test="sitemap:priority >= 0.5">priority-medium</xsl:when>
							<xsl:otherwise>priority-low</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
						<xsl:value-of select="sitemap:priority" />
					</td>
				</tr>
				</xsl:for-each>
			</tbody>
		</table>
	</body>
</html>
</xsl:template>
</xsl:stylesheet>