<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
  <xsl:output method="html" doctype-system="about:legacy-compat" indent="yes" />
  
  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>XML Sitemap | Syntax Toolbox</title>
        <style>
          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #2d3748;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f8fafc;
          }
          h1 {
            color: #1e40af;
            border-bottom: 2px solid #3b82f6;
            padding-bottom: 10px;
            margin-bottom: 20px;
          }
          .info {
            background-color: #e0f2fe;
            padding: 15px;
            border-radius: 6px;
            margin-bottom: 20px;
            font-size: 0.95em;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
            background-color: white;
          }
          th, td {
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid #e2e8f0;
          }
          th {
            background-color: #3b82f6;
            color: white;
            font-weight: 600;
          }
          tr:hover {
            background-color: #f0f9ff;
          }
          .footer {
            margin-top: 25px;
            font-size: 0.9em;
            color: #64748b;
            text-align: center;
            padding-top: 15px;
            border-top: 1px solid #e2e8f0;
          }
          a {
            color: #2563eb;
            text-decoration: none;
            font-weight: 500;
          }
          a:hover {
            text-decoration: underline;
            color: #1d4ed8;
          }
          .priority-high {
            color: #10b981;
            font-weight: 600;
          }
          .priority-medium {
            color: #f59e0b;
          }
          .priority-low {
            color: #64748b;
          }
          @media (max-width: 768px) {
            table {
              font-size: 0.9em;
            }
            th, td {
              padding: 8px 10px;
            }
          }
        </style>
      </head>
      <body>
        <h1>Syntax Toolbox Sitemap</h1>
        <div class="info">
          This sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)" /></strong> URLs. 
          Last generated: <strong><xsl:value-of select="sitemap:urlset/sitemap:url[1]/sitemap:lastmod" /></strong>.
        </div>
        <table>
          <thead>
            <tr>
              <th>URL</th>
              <th>Last Modified</th>
              <th>Change Frequency</th>
              <th>Priority</th>
            </tr>
          </thead>
          <tbody>
            <xsl:for-each select="sitemap:urlset/sitemap:url">
              <tr>
                <td>
                  <a href="{sitemap:loc}">
                    <xsl:value-of select="sitemap:loc" />
                  </a>
                </td>
                <td>
                  <xsl:value-of select="sitemap:lastmod" />
                </td>
                <td>
                  <xsl:value-of select="sitemap:changefreq" />
                </td>
                <td>
                  <xsl:attribute name="class">
                    <xsl:choose>
                      <xsl:when test="sitemap:priority >= 0.9">priority-high</xsl:when>
                      <xsl:when test="sitemap:priority >= 0.5">priority-medium</xsl:when>
                      <xsl:otherwise>priority-low</xsl:otherwise>
                    </xsl:choose>
                  </xsl:attribute>
                  <xsl:value-of select="sitemap:priority" />
                </td>
              </tr>
            </xsl:for-each>
          </tbody>
        </table>
        <div class="footer">
          Generated by <a href="https://syntaxtoolbox.com" target="_blank">Syntax Toolbox</a> | 
          <a href="https://syntaxtoolbox.com/tools" target="_blank">Tools</a> | 
          <a href="https://www.sitemaps.org" target="_blank">About Sitemaps</a>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>